spring:
  application:
    name: mhs-server
  profiles:
    active: dev
  config:
    import: optional:configserver:http://configuser:configpassword@localhost:8888?fail-fast=true&max-attempts=10&max-interval=1500&multiplier=1.2&initial-interval=1100