version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: contactdb
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./postgres-init/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh

  redis:
    image: redis:7
    container_name: redis
    networks:
      - backend
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest      # Change to your desired username
      RABBITMQ_DEFAULT_PASS: guest   # Change to your desired password
    ports:
      - "5672:5672"   # RabbitMQ default port for messaging
      - "15672:15672" # RabbitMQ management console port
    networks:
      - backend
      
  eureka-server:
    build:
      context: ./eureka 
      dockerfile: Dockerfile 
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - backend

  config-server:
    build:
      context: ./config_server 
      dockerfile: Dockerfile 
    container_name: config-server
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8888:8888" 
    networks:
      - backend
      
      
  cms:
    build:
      context: ./cms 
      dockerfile: Dockerfile 
    container_name: cms-container
    ports:
      - "8080:8080"
    links:
     - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - config-server
      - redis
    networks:
      - backend
      
  irs:
    build:
      context: ./irs 
      dockerfile: Dockerfile 
    container_name: irs-container
    ports:
      - "8081:8081"
    links:
     - redis
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - config-server
      - redis
    networks:
      - backend

networks:
  backend:
    driver: bridge

