server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/contactdb
    username: user
    password: password
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

redis:
  host: redis-cache  # Use the environment variable
  port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip: false
