server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interaction_db
    username: user
    password: password
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  amqp:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
    deserialization:
      trust:
        all: true

redis:
  host: localhost
  port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip: false
