server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/interaction_db
    username: user
    password: password
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
    deserialization:
      trust:
        all: true

  redis:
    host: redis
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip: false
